### ISSUE TITLE
Bills are Deleted When Adding to Credit Card

### ISSUE THREAD

**Issue by TornadoGamer10** [FifouBE/EconomyInc#46] opened 2021-05-23 01:25 UTC
I have been having a bug where if I have multiple stacks on bills in my inventory and I add press the button to add them to my balance, it takes one bill from each stack and only gives the equivalent of 1 bill. This ends up deleting all of the money in all but 1 stack of bills.

https://user-images.githubusercontent.com/61255007/119245070-22658b00-bb2b-11eb-831d-90ed2882a0a9.mp4

**Comment by Florent98** [comment] 2021-05-23 15:23
Hello this is a duplicate of issue #37 and #43. It has been fixed and will be pushed with version 1.7 of the mod. Thanks for the report! :)

**Closed as completed by Florent98** 2021-05-23 15:23 UTC
Labels: bug, duplicate
